-- 코드를 작성해주세요
-- 내가 누군가의 부모가 아닌게 최종 완결 아이템이다

SELECT ITEM_ID, ITEM_NAME, RARITY 
FROM ITEM_INFO
WHERE 
ITEM_ID NOT IN (
    SELECT DISTINCT PARENT_ITEM_ID 
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC;

# SELECT DISTINCT(PARENT_ITEM_ID) FROM ITEM_TREE