-- 코드를 작성해주세요

SELECT TEMP.Q AS QUARTER, COUNT(*) AS ECOLI_COUNT

FROM (
    SELECT 
    CASE 
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m') BETWEEN 1 AND 3 THEN '1Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m') BETWEEN 4 AND 6 THEN '2Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m') BETWEEN 7 AND 9 THEN '3Q'
        ELSE '4Q'
    END AS Q
FROM ECOLI_DATA) AS TEMP
GROUP BY TEMP.Q
ORDER BY QUARTER ASC